// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugdswubedmrgtjiogrpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnZHN3dWJlZG1yZ3RqaW9ncnBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTI0OTQsImV4cCI6MjA1ODU2ODQ5NH0.DWEa2_4S3p39W4bKx2_p344rXXJZyPIEA7J2mv4fsDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);